# Generated by Django 6.1 on 2026-08-06 03:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CLIENT', 'Cliente'), ('SUPPLIER', 'Fornecedor'), ('PARTNER', 'Parceiro'), ('PUBLIC_BODY', 'Órgão Público'), ('PROFESSIONAL', 'Profissional'), ('SUBCONTRACTOR', 'Subcontratado')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome ou Razão Social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('person_type', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2, verbose_name='Tipo de Pessoa')),
                ('document', models.CharField(blank=True, max_length=20, verbose_name='CPF / CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('roles', models.ManyToManyField(related_name='contacts', to='contacts.contactrole', verbose_name='Funções')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora')),
                ('interaction_type', models.CharField(choices=[('REUNIAO', 'Reunião'), ('LIGACAO', 'Ligação'), ('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp'), ('VISITA', 'Visita Técnica'), ('OUTRO', 'Outro')], default='REUNIAO', max_length=50, verbose_name='Tipo')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('next_action', models.CharField(blank=True, max_length=255, verbose_name='Próxima Ação')),
                ('next_action_deadline', models.DateField(blank=True, null=True, verbose_name='Prazo da Próxima Ação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='contacts.contact', verbose_name='Contato')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
                'ordering': ['-date'],
            },
        ),
    ]
