# Generated by Django 6.1.1 on 2026-09-30 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2)),
                ('razao_social_nome', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_cnpj', models.CharField(db_index=True, max_length=18, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=50, null=True)),
                ('classificacoes', models.JSONField(blank=True, default=list, help_text='Ex: LEAD, CLIENTE, FORNECEDOR, PARCEIRO, ORGAO_PUBLICO')),
                ('email_principal', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone_principal', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('is_obra', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone_direto', models.CharField(blank=True, max_length=20, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='contacts.contact')),
            ],
        ),
    ]
