# Generated by Django 6.1 on 2026-08-06 03:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('contacts', '0001_initial'),
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Número da NF / Fatura')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Faturado (R$)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Recebido (R$)')),
                ('status', models.CharField(choices=[('EM_ABERTO', 'Em Aberto'), ('PAGO', 'Pago'), ('PARCIALMENTE_PAGO', 'Parcialmente Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='EM_ABERTO', max_length=50, verbose_name='Status do Pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='contacts.contact', verbose_name='Cliente')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='commercial.contract', verbose_name='Contrato de Origem')),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='measurements.measurement', verbose_name='Medição de Origem')),
            ],
            options={
                'verbose_name': 'Fatura / Nota Fiscal',
                'verbose_name_plural': 'Faturas / Notas Fiscais',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
