# Generated by Django 6.0.8 on 2026-10-01 11:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='endereço de e-mail')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='primeiro nome')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='sobrenome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='equipe')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sector', models.CharField(choices=[('ADMINISTRATIVO', 'Administrativo'), ('COMERCIAL', 'Comercial'), ('TECNICO', 'Técnico (Engenharia)'), ('FINANCEIRO', 'Financeiro'), ('TI', 'TI / Infraestrutura')], db_index=True, default='TECNICO', max_length=25, verbose_name='setor')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='cargo')),
                ('crea_number', models.CharField(blank=True, help_text='Registro profissional do engenheiro ou técnico no CREA.', max_length=30, verbose_name='número CREA/UF')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuário',
                'verbose_name_plural': 'perfis de usuários',
            },
        ),
    ]
