# Generated by Django 6.0.8 on 2026-10-01 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sector',
        ),
        migrations.CreateModel(
            name='UserSectorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sector', models.CharField(choices=[('ADMINISTRATIVO', 'Administrativo'), ('COMERCIAL', 'Comercial'), ('TECNICO', 'Técnico (Engenharia)'), ('FINANCEIRO', 'Financeiro'), ('TI', 'TI / Infraestrutura')], db_index=True, max_length=25, verbose_name='setor corporativo')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Assistente / Estagiário'), (2, 'Engenheiro / Analista'), (3, 'Coordenador / Gerente'), (4, 'Diretor / Sócio / RT')], db_index=True, default=2, verbose_name='nível hierárquico')),
                ('is_primary', models.BooleanField(default=False, help_text='Identifica o setor padrão para relatórios e exibição principal.', verbose_name='setor principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'atribuição de setor e alçada',
                'verbose_name_plural': 'atribuições de setores e alçadas',
                'ordering': ['-level', 'sector'],
                'unique_together': {('user', 'sector')},
            },
        ),
    ]
