# Generated by Django 6.0.8 on 2026-10-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_sector_usersectorassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone'),
        ),
    ]
