# Generated by Django 6.1 on 2026-08-07 23:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código do Projeto')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('service_type', models.CharField(choices=[('GEOTECNIA', 'Projetos e Consultoria em Geotecnia'), ('FUNDACOES', 'Projetos de Fundação'), ('CONTENCOES', 'Soluções de Contenção'), ('MUROS', 'Muros de Arrimo'), ('OBRAS_TERRA', 'Obras de Terra'), ('ESTRUTURAS', 'Estruturas'), ('PAVIMENTACAO', 'Pavimentação'), ('CONSULTORIA', 'Consultoria Técnica')], default='GEOTECNIA', max_length=50, verbose_name='Tipo de Serviço')),
                ('description', models.TextField(verbose_name='Descrição do Projeto')),
                ('site_address', models.CharField(blank=True, max_length=255, verbose_name='Endereço da Obra')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Município')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('expected_completion_date', models.DateField(verbose_name='Data Prevista de Conclusão')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='Data Efetiva de Conclusão')),
                ('status', models.CharField(choices=[('EM_ELABORACAO', 'Em Elaboração'), ('EM_ANDAMENTO', 'Em Andamento'), ('EM_REVISAO', 'Em Revisão'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação'), ('PARALISADO', 'Paralisado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='contacts.contato', verbose_name='Cliente')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='commercial.contract', verbose_name='Contrato de Origem')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Gerente de Projeto')),
                ('technical_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_projects', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Técnico (RT)')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título da Entrega')),
                ('description', models.TextField(blank=True, verbose_name='Descrição dos Documentos / Relatórios')),
                ('delivery_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Entrega')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='AGUARDANDO_APROVACAO', max_length=50, verbose_name='Status de Aprovação')),
                ('notes', models.TextField(blank=True, verbose_name='Observações do Cliente / Parecer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Entregue por')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Tarefa / Etapa')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Prazo de Conclusão')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('EM_REVISAO', 'Em Revisão'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
