# Generated by Django 6.1.1 on 2026-09-30 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=255)),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('BRIEFING', 'Briefing'), ('ESTUDOS_PRELIMINARES', 'Estudos Preliminares'), ('CALCULO_DIMENSIONAMENTO', 'Cálculo e Dimensionamento'), ('DESENHO_DETALHAMENTO', 'Desenho e Detalhamento'), ('REVISAO_INTERNA', 'Revisão Interna'), ('ENTREGUE', 'Entregue')], default='BRIEFING', max_length=30)),
                ('percentual_avanco', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ordem_servico', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='commercial.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_etapa', models.CharField(max_length=150)),
                ('concluida', models.BooleanField(default=False)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('A_FAZER', 'A Fazer'), ('EM_ANDAMENTO', 'Em Andamento'), ('IMPEDIMENTO', 'Com Impedimento'), ('CONCLUIDA', 'Concluída')], default='A_FAZER', max_length=20)),
                ('horas_previstas', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('horas_gastas', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.projectphase')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
