# Generated by Django 6.1.1 on 2026-09-30 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(default=1)),
                ('data_vencimento', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('A_VENCER', 'A Vencer'), ('VENCIDA', 'Vencida'), ('LIQUIDADA', 'Liquidada')], default='A_VENCER', max_length=20)),
            ],
            options={
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nfse', models.CharField(max_length=30, unique=True)),
                ('codigo_verificacao', models.CharField(blank=True, max_length=50)),
                ('data_emissao', models.DateField(default=datetime.date.today)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aliquota_iss', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('retencoes_federais', models.JSONField(blank=True, default=dict)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('EMITIDA', 'Emitida'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='EMITIDA', max_length=20)),
                ('arquivo_xml', models.FileField(blank=True, null=True, upload_to='invoices/xml/')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='invoices/pdf/')),
            ],
        ),
    ]
