# Generated by Django 6.1.1 on 2026-09-30 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinvoice',
            name='medicao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='measurements.measurementsheet'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='invoices.serviceinvoice'),
        ),
    ]
