# Generated by Django 6.0.8 on 2026-10-02 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Nome do Marcador')),
                ('color', models.CharField(default='#2563eb', max_length=20, verbose_name='Cor Hexadecimal')),
            ],
            options={
                'verbose_name': 'Marcador de Contato',
                'verbose_name_plural': 'Marcadores de Contatos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('COMPANY', 'Pessoa Jurídica (Empresa)'), ('INDIVIDUAL', 'Pessoa Física (Individual)')], db_index=True, default='COMPANY', max_length=15, verbose_name='Tipo de Contato')),
                ('address_type', models.CharField(choices=[('CONTACT', 'Contato'), ('INVOICE', 'Endereço de Cobrança'), ('DELIVERY', 'Endereço de Entrega / Canteiro'), ('OTHER', 'Outro Endereço')], db_index=True, default='CONTACT', max_length=15, verbose_name='Tipo de Endereço / Vínculo')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Nome / Razão Social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('doc_type', models.CharField(choices=[('CNPJ', 'CNPJ'), ('CPF', 'CPF')], default='CNPJ', max_length=10, verbose_name='Tipo de Documento')),
                ('doc_number', models.CharField(blank=True, db_index=True, max_length=25, verbose_name='Número do Documento')),
                ('state_registration', models.CharField(blank=True, max_length=30, verbose_name='Inscrição Estadual (IE)')),
                ('municipal_registration', models.CharField(blank=True, max_length=30, verbose_name='Inscrição Municipal (IM)')),
                ('suframa_code', models.CharField(blank=True, max_length=30, verbose_name='Código SUFRAMA')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Estado / UF')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('country', models.CharField(default='Brasil', max_length=50, verbose_name='País')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefone')),
                ('mobile', models.CharField(blank=True, max_length=25, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Site Oficial')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Cargo / Função')),
                ('payment_terms', models.CharField(blank=True, max_length=50, verbose_name='Condições de Pagamento')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='contacts/avatars/', verbose_name='Foto / Logotipo')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Anotações Internas')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='contacts.contact', verbose_name='Empresa Vinculada')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor / Responsável')),
                ('tags', models.ManyToManyField(blank=True, related_name='contacts', to='contacts.contacttag', verbose_name='Marcadores')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='contacts_co_name_ce8db5_idx'), models.Index(fields=['doc_number', 'is_active'], name='contacts_co_doc_num_3eeb0b_idx'), models.Index(fields=['city', 'state'], name='contacts_co_city_cde9cc_idx')],
            },
        ),
    ]
