# Generated by Django 6.0.8 on 2026-10-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, default='Brasil', max_length=50, verbose_name='País'),
        ),
    ]
