# Generated by Django 6.0.8 on 2026-10-02 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company_subtype',
            field=models.CharField(blank=True, choices=[('MATRIZ', 'Matriz / Holding Controladora'), ('SPE', 'Sociedade de Propósito Específico (SPE / Empreendimento)'), ('FILIAL', 'Filial / Unidade Regional'), ('CONSORCIO', 'Consórcio de Empresas'), ('OUTRO', 'Outro')], db_index=True, default='MATRIZ', help_text='Classificação jurídica: Matriz, SPE, Filial ou Consórcio.', max_length=20, verbose_name='Subtipo Empresarial'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='contacts.contact', verbose_name='Empresa Vinculada (Holding / Controladora)'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_type', 'company_subtype'], name='contacts_co_contact_c1bc8a_idx'),
        ),
    ]
