# Generated by Django 6.0.8 on 2026-10-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_company_subtype_alter_contact_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número'),
        ),
    ]
