# Generated by Django 6.1.1 on 2026-09-30 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_de_custo', models.CharField(choices=[('ADMINISTRATIVO', 'Administrativo'), ('OPERACIONAL_GEOTECNIA', 'Operacional Geotécnico'), ('COMERCIAL', 'Comercial'), ('TI_SOFTWARES', 'TI & Softwares')], default='ADMINISTRATIVO', max_length=30)),
                ('categoria_despesa', models.CharField(help_text='Ex: Laboratório de Solos, Combustível, Softwares', max_length=100)),
                ('descricao', models.CharField(max_length=255)),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField(db_index=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('comprovante_fiscal', models.FileField(blank=True, null=True, upload_to='financial/fiscal/')),
                ('comprovante_pagamento', models.FileField(blank=True, null=True, upload_to='financial/payments/')),
                ('status', models.CharField(choices=[('AGUARDANDO_APROVACAO', 'Aguardando Aprovação'), ('APROVADA', 'Aprovada'), ('LIQUIDADA', 'Liquidada'), ('CANCELADA', 'Cancelada')], default='APROVADA', max_length=25)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='contacts.contact')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.project')),
            ],
            options={
                'ordering': ['data_vencimento'],
            },
        ),
    ]
