# Generated by Django 6.1 on 2026-08-07 23:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, verbose_name='Número do Documento / NF / Boleto')),
                ('category', models.CharField(choices=[('MATERIAIS_OBRA', 'Insumos / Materiais de Obra'), ('LABORATORIO_ENSAIOS', 'Laboratório / Ensaios de Solo'), ('EQUIPAMENTOS', 'Equipamentos / Aluguel de Maquinário'), ('SUBCONTRATADOS', 'Subcontratados / Serviços Técnicos'), ('IMPOSTOS_TAXAS', 'Impostos / Taxas / ART'), ('UTILIDADES_ESCRITORIO', 'Utilidades / Despesas de Escritório'), ('OUTROS', 'Outras Despesas')], default='MATERIAIS_OBRA', max_length=50, verbose_name='Categoria da Despesa')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor a Pagar (R$)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Pago (R$)')),
                ('status', models.CharField(choices=[('EM_ABERTO', 'Em Aberto'), ('PAGO', 'Pago'), ('PARCIALMENTE_PAGO', 'Parcialmente Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='EM_ABERTO', max_length=50, verbose_name='Status do Pagamento')),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='payables/bills/%Y/%m/', verbose_name='Anexo da Conta (PDF / Imagem)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações / Histórico de Compliance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payable_bills', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_bills', to='projects.project', verbose_name='Projeto (Apropriação de Custo)')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payable_bills', to='contacts.contato', verbose_name='Fornecedor / Favorecido')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Efetivo Pagamento')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Pago nesta Transação (R$)')),
                ('payment_method', models.CharField(choices=[('PIX', 'Pix'), ('TRANSFERENCIA', 'Transferência Bancária (TED/DOC)'), ('BOLETO', 'Boleto Bancário'), ('CARTAO', 'Cartão de Crédito/Débito'), ('DINHEIRO', 'Dinheiro')], default='PIX', max_length=50, verbose_name='Forma de Pagamento')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payables/receipts/%Y/%m/', verbose_name='Comprovante / Recibo (PDF / Imagem)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payables.payablebill', verbose_name='Conta a Pagar')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Comprovante de Pagamento',
                'verbose_name_plural': 'Comprovantes de Pagamento',
                'ordering': ['-payment_date'],
            },
        ),
    ]
