# Generated by Django 6.1 on 2026-08-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial [conflicted]'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrador'), ('MANAGER', 'Gerente'), ('COLLABORATOR', 'Colaborador')], default='COLLABORATOR', max_length=20, verbose_name='Nível de Acesso / Perfil'),
        ),
    ]
