# Generated by Django 6.1.1 on 2026-09-30 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SONDAGEM_SPT_CPTU', 'Sondagem SPT/CPTU'), ('MEMORIA_CALCULO', 'Memória de Cálculo'), ('PRANCHA_CAD_BIM', 'Prancha CAD/BIM'), ('RELATORIO_TECNICO', 'Relatório Técnico'), ('ART_CREA', 'ART CREA'), ('OUTRO', 'Outro')], max_length=30)),
                ('codigo_identificador', models.CharField(help_text='Ex: PG-PROJ-01-EST-001', max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisao', models.CharField(blank=True, max_length=10)),
                ('arquivo', models.FileField(upload_to='edms_vault/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('EM_ELABORACAO', 'Em Elaboração'), ('APROVADO_INTERNO', 'Aprovado Internamente'), ('EMITIDO_CLIENTE', 'Emitido para o Cliente'), ('APROVADO_CLIENTE', 'Aprovado pelo Cliente')], default='EM_ELABORACAO', max_length=30)),
                ('notas_alteracao', models.TextField(blank=True, null=True)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
