# Generated by Django 6.1 on 2026-08-07 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Documento')),
                ('category', models.CharField(choices=[('DESENHO_CAD', 'Desenho / Prancha CAD'), ('MODELO_BIM', 'Modelo 3D / BIM'), ('MEMORIAL_CALCULO', 'Memorial de Cálculo'), ('LAUDO_GEOTECNICO', 'Laudo Geotécnico / Vistoria'), ('SONDAGEM_SPT', 'Ensaio de Sondagem SPT'), ('ART_CREA', 'ART / Anotação de Resp. Técnica'), ('CONTRATO_ADM', 'Contrato / Documento Administrativo'), ('OUTRO', 'Outro Documento')], default='DESENHO_CAD', max_length=50, verbose_name='Categoria Técnica')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Arquivo')),
                ('revision', models.CharField(default='R00', max_length=10, verbose_name='Código da Revisão')),
                ('status', models.CharField(choices=[('EM_ELABORACAO', 'Em Elaboração'), ('EM_REVISAO', 'Em Revisão'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('OBSOLETO', 'Obsoleto')], default='EM_ELABORACAO', max_length=50, verbose_name='Status de Aprovação')),
                ('notes', models.TextField(blank=True, verbose_name='Observações / Histórico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project', verbose_name='Projeto Associado')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento Técnico',
                'verbose_name_plural': 'Documentos Técnicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.CharField(max_length=10, verbose_name='Revisão')),
                ('file', models.FileField(upload_to='documents/revisions/%Y/%m/', verbose_name='Arquivo da Revisão')),
                ('changes_summary', models.TextField(verbose_name='Descrição das Alterações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.document', verbose_name='Documento Principal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Revisão Documental',
                'verbose_name_plural': 'Revisões Documentais',
                'ordering': ['-created_at'],
            },
        ),
    ]
