# Generated by Django 6.1 on 2026-08-07 23:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Número da Medição')),
                ('measurement_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Medição')),
                ('period_start', models.DateField(verbose_name='Período de Referência - Início')),
                ('period_end', models.DateField(verbose_name='Período de Referência - Fim')),
                ('measured_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Medido (R$)')),
                ('percentage_completed', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='% Concluído da Etapa')),
                ('description', models.TextField(verbose_name='Descrição dos Serviços Medidos')),
                ('status', models.CharField(choices=[('EM_ELABORACAO', 'Em Elaboração'), ('EM_REVISAO', 'Em Revisão'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='EM_ELABORACAO', max_length=50, verbose_name='Status da Medição')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_measurements', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='commercial.contract', verbose_name='Contrato de Origem')),
                ('measured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measured_items', to=settings.AUTH_USER_MODEL, verbose_name='Medido por')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Medição',
                'verbose_name_plural': 'Medições',
                'ordering': ['-measurement_date', '-created_at'],
            },
        ),
    ]
