# Generated by Django 6.1.1 on 2026-09-30 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_medicao', models.PositiveIntegerField(blank=True)),
                ('competencia', models.DateField(help_text='Mês/Ano de referência')),
                ('valor_total_medido', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDA_TECNICO', 'Submetida pelo Técnico'), ('APROVADA_CLIENTE', 'Aprovada pelo Cliente'), ('REJEITADA', 'Rejeitada'), ('FATURADA', 'Faturada')], default='RASCUNHO', max_length=25)),
                ('documento_comprovatorio', models.FileField(blank=True, null=True, upload_to='measurements/')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='commercial.contract')),
            ],
            options={
                'ordering': ['contrato', 'numero_medicao'],
                'unique_together': {('contrato', 'numero_medicao')},
            },
        ),
        migrations.CreateModel(
            name='MeasurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discriminacao', models.CharField(max_length=255)),
                ('percentual_executado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_apurado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('folha_medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='measurements.measurementsheet')),
            ],
        ),
    ]
