# Generated by Django 6.0.8 on 2026-10-05 17:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_contact_company_subtype_alter_contact_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposal_code', models.CharField(db_index=True, help_text='Padrão formal Pangea: PROP-XXXXA/AAAA (ex: PROP-1685A/2026)', max_length=50, unique=True, verbose_name='Código da Proposta')),
                ('project_name', models.CharField(db_index=True, max_length=255, verbose_name='Nome da Obra / Empreendimento')),
                ('project_location', models.CharField(default='Manaus/AM', max_length=255, verbose_name='Localização da Obra')),
                ('validity_days', models.PositiveIntegerField(default=30, verbose_name='Prazo de Validade (Dias)')),
                ('execution_lead_time_days', models.PositiveIntegerField(default=20, help_text='Contagem estritamente suspensa até a aprovação de todos os insumos da contratante.', verbose_name='Prazo de Execução (Dias Corridos a partir de D0)')),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Global (R$)')),
                ('payment_terms_desc', models.TextField(default='50% de entrada no aceite da proposta e 50% na entrega final do projeto executivo.', verbose_name='Forma de Pagamento e Condições')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada ao Cliente'), ('EM_REVISAO', 'Em Revisão Solicitada pelo Cliente'), ('ACEITA', 'Aceita pelo Cliente (Aprovada)'), ('DECLINADA', 'Recusada pelo Cliente'), ('EXPIRADA', 'Validade Expirada')], db_index=True, default='RASCUNHO', max_length=25, verbose_name='Status da Proposta')),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de Acesso Público')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada ao Cliente em')),
                ('expires_at', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data Limite de Validade')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceita em')),
                ('acceptance_signer_name', models.CharField(blank=True, max_length=150, verbose_name='Nome do Signatário')),
                ('acceptance_signer_doc', models.CharField(blank=True, max_length=25, verbose_name='CPF/CNPJ do Signatário')),
                ('acceptance_signer_role', models.CharField(blank=True, max_length=100, verbose_name='Cargo / Função do Signatário')),
                ('acceptance_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP do Aceite')),
                ('acceptance_user_agent', models.TextField(blank=True, verbose_name='Navegador / Dispositivo')),
                ('acceptance_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash SHA-256 do Manifesto')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Recusa')),
                ('revision_notes', models.TextField(blank=True, verbose_name='Comentários de Revisão da Contratante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='contacts.contact', verbose_name='Cliente / Contratante')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Consultor Comercial')),
                ('technical_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technical_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Técnico (Engenheiro com CREA)')),
            ],
            options={
                'verbose_name': 'Proposta Comercial',
                'verbose_name_plural': 'Propostas Comerciais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código do Contrato')),
                ('contract_type', models.CharField(choices=[('PADRAO_ERP', 'Minuta Padrão ERPangea'), ('MINUTA_CLIENTE', 'Contrato Externo (Minuta do Cliente)')], default='PADRAO_ERP', max_length=20, verbose_name='Modelo de Minuta')),
                ('contract_html_body', models.TextField(verbose_name='Texto das Cláusulas Contratuais')),
                ('status', models.CharField(choices=[('MINUTA', 'Minuta em Elaboração'), ('AGUARDANDO_ASSINATURA', 'Aguardando Assinatura'), ('ASSINADO', 'Contrato Assinado'), ('PENDENTE_INSUMOS', 'Pendente de Insumos da Contratante'), ('MISE_EN_SERVICE', 'Em Execução (Mise en Service Ativo - D0)'), ('CONCLUIDO', 'Concluído e Entregue'), ('CANCELADO', 'Cancelado')], db_index=True, default='MINUTA', max_length=25, verbose_name='Situação do Contrato')),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='commercial/contracts/', verbose_name='Contrato Assinado (PDF)')),
                ('signed_at', models.DateField(blank=True, null=True, verbose_name='Data de Assinatura')),
                ('crea_art_number', models.CharField(blank=True, help_text='Registro de Anotação de Responsabilidade Técnica', max_length=50, verbose_name='Número da ART no CREA-AM')),
                ('crea_art_file', models.FileField(blank=True, null=True, upload_to='commercial/arts/', verbose_name='Comprovante da ART')),
                ('crea_art_status', models.CharField(default='PENDENTE', max_length=20, verbose_name='Status da ART')),
                ('d0_trigger_date', models.DateField(blank=True, help_text='Início efetivo da contagem do prazo contratual', null=True, verbose_name='Marco Zero (D0)')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='Data Final de Entrega do Projeto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='commercial.commercialproposal')),
            ],
            options={
                'verbose_name': 'Contrato Formal',
                'verbose_name_plural': 'Contratos Formais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalInputRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_item_type', models.CharField(choices=[('SONDAGEM_SPT', 'Furos de Sondagem SPT segundo a NBR 6484'), ('PLANTA_CARGAS', 'Planta de Cargas com Esforços Axiais, Horizontais e Momentos'), ('ARQUITETURA_DWG', 'Projetos Arquitetônicos e Implantação em formato DWG'), ('LEVANTAMENTO_TOPOGRAFICO', 'Levantamento Planialtimétrico Cadastral (DWG)'), ('PROJETO_ESTRUTURAL_DWG', 'Projeto Estrutural de Concreto ou Estrutura Metálica (DWG)'), ('OUTRO', 'Outro Documento / Insumo Técnico')], max_length=30, verbose_name='Insumo Obrigatório')),
                ('description', models.CharField(default='Fornecimento obrigatório pela contratante conforme normas técnicas.', max_length=255, verbose_name='Especificação Técnica Mínima')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Bloqueia Início das Obras (D0)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Entrega pelo Cliente'), ('EM_ANALISE', 'Em Análise Técnica pelo Geotécnico'), ('APROVADO', 'Aprovado pelo Responsável Técnico'), ('REJEITADO', 'Inconforme / Rejeitado (Exige Nova Emissão)')], default='PENDENTE', max_length=20, verbose_name='Situação')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='commercial/inputs/', verbose_name='Arquivo Recebido')),
                ('technical_notes', models.TextField(blank=True, verbose_name='Parecer do Engenheiro Geotécnico')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Homologado em')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_requirements', to='commercial.commercialproposal')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_inputs', to=settings.AUTH_USER_MODEL, verbose_name='Validado Por')),
            ],
            options={
                'verbose_name': 'Insumo Técnico Obrigatório',
                'verbose_name_plural': 'Insumos Técnicos Obrigatórios',
                'ordering': ['required_item_type'],
            },
        ),
        migrations.CreateModel(
            name='ProposalScopeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('FUNDACOES', 'Dimensionamento de Fundações Superficiais e Profundas (NBR 6122 / NBR 6118)'), ('ESTABILIDADE_TALUDES', 'Análise de Estabilidade de Encostas e Taludes (NBR 11682)'), ('CONTENCOES', 'Projetos Geotécnicos e Estruturais de Contenções de Divisa'), ('CONSULTORIA_PERICIA', 'Consultoria Geotécnica e Laudos Periciais em Obra')], max_length=30, verbose_name='Disciplina / Serviço')),
                ('nbr_references', models.CharField(default='NBR 6122 / NBR 6118', help_text='Ex: ABNT NBR 6122:2019 e NBR 6118:2023', max_length=150, verbose_name='Normas ABNT Aplicáveis')),
                ('description', models.TextField(verbose_name='Memorial Descritivo do Escopo')),
                ('subtotal_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal (R$)')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_items', to='commercial.commercialproposal')),
            ],
            options={
                'verbose_name': 'Item de Escopo da Proposta',
                'verbose_name_plural': 'Itens de Escopo da Proposta',
                'ordering': ['service_type'],
            },
        ),
    ]
