# Generated by Django 6.0.8 on 2026-10-07 14:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDiscipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome da Disciplina')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disciplina Técnica',
                'verbose_name_plural': 'Disciplinas Técnicas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalInputType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='Tipo de Insumo')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Código de Referência')),
                ('default_description', models.CharField(blank=True, default='Fornecimento obrigatório pela contratante conforme normas técnicas.', max_length=255, verbose_name='Especificação Técnica Mínima')),
                ('is_mandatory_default', models.BooleanField(default=True, verbose_name='Bloqueia D0 por Padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Insumo Técnico',
                'verbose_name_plural': 'Tipos de Insumos Técnicos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='proposalinputrequirement',
            name='required_item_type',
            field=models.CharField(blank=True, max_length=180, verbose_name='Insumo Obrigatório'),
        ),
        migrations.AlterField(
            model_name='proposalscopeitem',
            name='service_type',
            field=models.CharField(blank=True, max_length=180, verbose_name='Disciplina / Serviço'),
        ),
        migrations.AddField(
            model_name='proposalscopeitem',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_items', to='commercial.technicaldiscipline', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='proposalinputrequirement',
            name='input_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='commercial.technicalinputtype', verbose_name='Tipo do Insumo'),
        ),
        migrations.CreateModel(
            name='TechnicalServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='Tipo de Serviço')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Código de Referência')),
                ('default_nbr_references', models.CharField(blank=True, help_text='Ex: ABNT NBR 6122:2019 e NBR 6118:2023', max_length=150, verbose_name='Normas ABNT Padrão')),
                ('default_description', models.TextField(blank=True, verbose_name='Memorial Descritivo Padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_types', to='commercial.technicaldiscipline', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço Técnico',
                'verbose_name_plural': 'Tipos de Serviços Técnicos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='proposalscopeitem',
            name='service_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_items', to='commercial.technicalservicetype', verbose_name='Tipo de Serviço'),
        ),
    ]
