# Generated by Django 6.0.8 on 2026-10-08 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_populate_real_engineering_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproposal',
            name='unlock_reason',
            field=models.TextField(blank=True, verbose_name='Justificativa do Desbloqueio'),
        ),
        migrations.AddField(
            model_name='commercialproposal',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desbloqueada em'),
        ),
        migrations.AddField(
            model_name='commercialproposal',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Desbloqueada Por'),
        ),
        migrations.AlterField(
            model_name='proposalscopeitem',
            name='nbr_references',
            field=models.CharField(blank=True, default='', help_text='Ex: ABNT NBR 6122:2019 e NBR 6118:2023', max_length=150, verbose_name='Normas ABNT Aplicáveis'),
        ),
    ]
