# Generated by Django 6.0.8 on 2026-10-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_commercialproposal_unlock_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalinputrequirement',
            name='category',
            field=models.CharField(choices=[('TECNICO', 'Técnico'), ('ADMINISTRATIVO', 'Administrativo')], default='TECNICO', max_length=20, verbose_name='Tipo de Insumo'),
        ),
        migrations.AddField(
            model_name='technicalinputtype',
            name='category',
            field=models.CharField(choices=[('TECNICO', 'Técnico'), ('ADMINISTRATIVO', 'Administrativo')], default='TECNICO', max_length=20, verbose_name='Tipo de Insumo'),
        ),
        migrations.AlterField(
            model_name='technicalinputtype',
            name='name',
            field=models.CharField(max_length=180, unique=True, verbose_name='Insumo'),
        ),
    ]
