# Generated by Django 6.0.8 on 2026-10-01 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('LOGIN', 'Autenticação com Sucesso'), ('LOGOUT', 'Encerramento de Sessão'), ('FAILED_LOGIN', 'Tentativa Falha de Login'), ('EXPORT', 'Exportação de Dados')], db_index=True, max_length=20)),
                ('app_label', models.CharField(db_index=True, max_length=50)),
                ('model_name', models.CharField(db_index=True, max_length=50)),
                ('object_id', models.CharField(db_index=True, max_length=255)),
                ('object_repr', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'trilha de auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['app_label', 'model_name', 'object_id'], name='audit_log_a_app_lab_c7c4b8_idx'), models.Index(fields=['timestamp', 'action'], name='audit_log_a_timesta_eb4dba_idx')],
            },
        ),
    ]
