# Generated by Django 6.1 on 2026-08-07 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Origem do Lead')),
                ('service_of_interest', models.CharField(choices=[('GEOTECNIA', 'Projetos e Consultoria em Geotecnia'), ('FUNDACOES', 'Projetos de Fundação'), ('CONTENCOES', 'Soluções de Contenção'), ('MUROS', 'Muros de Arrimo'), ('OBRAS_TERRA', 'Obras de Terra'), ('ESTRUTURAS', 'Estruturas'), ('PAVIMENTACAO', 'Pavimentação'), ('CONSULTORIA', 'Consultoria Técnica')], default='GEOTECNIA', max_length=50, verbose_name='Serviço de Interesse')),
                ('description', models.TextField(verbose_name='Descrição da Oportunidade')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Estimado (R$)')),
                ('probability', models.PositiveIntegerField(default=50, verbose_name='Probabilidade (%)')),
                ('stage', models.CharField(choices=[('NOVO', 'Novo'), ('QUALIFICACAO', 'Qualificação'), ('CONTATO_REALIZADO', 'Contato Realizado'), ('PROPOSTA_EM_PREPARACAO', 'Proposta em Preparação'), ('CONVERTIDO', 'Convertido'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=50, verbose_name='Estágio')),
                ('expected_closing_date', models.DateField(blank=True, null=True, verbose_name='Previsão de Fechamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Comercial')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='contacts.contato', verbose_name='Contato / Cliente')),
            ],
            options={
                'verbose_name': 'Lead / Oportunidade',
                'verbose_name_plural': 'Leads / Oportunidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Número da Proposta')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('scope', models.TextField(verbose_name='Escopo do Projeto')),
                ('included_services', models.TextField(blank=True, verbose_name='Serviços Incluídos')),
                ('exclusions', models.TextField(blank=True, verbose_name='Exclusões de Escopo')),
                ('assumptions', models.TextField(blank=True, verbose_name='Premissas Técnicas')),
                ('execution_period_days', models.PositiveIntegerField(default=30, verbose_name='Prazo de Execução (Dias)')),
                ('validity_days', models.PositiveIntegerField(default=30, verbose_name='Validade da Proposta (Dias)')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total (R$)')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Condições de Pagamento')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_REVISAO', 'Em Revisão'), ('ENVIADA', 'Enviada'), ('EM_NEGOCIACAO', 'Em Negociação'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada'), ('EXPIRADA', 'Expirada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='contacts.contato', verbose_name='Cliente')),
                ('commercial_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Comercial')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='commercial.lead', verbose_name='Lead de Origem')),
                ('parent_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_versions', to='commercial.proposal', verbose_name='Versão Anterior')),
                ('technical_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Técnico (RT)')),
            ],
            options={
                'verbose_name': 'Proposta Técnica',
                'verbose_name_plural': 'Propostas Técnicas',
                'ordering': ['-created_at', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número do Contrato')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total (R$)')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Condições de Pagamento')),
                ('readjustment_index', models.CharField(blank=True, default='IPCA', max_length=50, verbose_name='Índice de Reajuste')),
                ('status', models.CharField(choices=[('EM_ELABORACAO', 'Em Elaboração'), ('EM_REVISAO', 'Em Revisão'), ('AGUARDANDO_ASSINATURA', 'Aguardando Assinatura'), ('ASSINADO', 'Assinado'), ('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('ENCERRADO', 'Encerrado'), ('RESCINDIDO', 'Rescindido')], default='EM_ELABORACAO', max_length=50, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contacts.contato', verbose_name='Cliente')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Gestor do Contrato')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='commercial.proposal', verbose_name='Proposta de Origem')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
    ]
