# Generated by Django 6.1.1 on 2026-09-30 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proposta', models.CharField(blank=True, max_length=50, unique=True)),
                ('disciplina_principal', models.CharField(choices=[('FUNDACOES', 'Fundações'), ('CONTENCOES', 'Contenções'), ('OBRAS_TERRA', 'Obras de Terra'), ('ESTRUTURAS', 'Estruturas'), ('PAVIMENTACAO', 'Pavimentação'), ('CONSULTORIA', 'Consultoria')], max_length=20)),
                ('valor_global', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada'), ('EM_NEGOCIACAO', 'Em Negociação'), ('APROVADA', 'Aprovada'), ('DECLINADA', 'Declinada')], default='RASCUNHO', max_length=20)),
                ('validade', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(blank=True, max_length=50, unique=True)),
                ('data_assinatura', models.DateField(blank=True, null=True)),
                ('data_vigencia_inicio', models.DateField()),
                ('data_vigencia_fim', models.DateField()),
                ('valor_total_contratado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('modalidade_cobranca', models.CharField(choices=[('MEDICAO_MENSAL', 'Medição Mensal'), ('PRECO_GLOBAL_MARCOS', 'Preço Global por Marcos'), ('HORAS_TECNICAS', 'Horas Técnicas')], max_length=25)),
                ('documento_assinado', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('proposta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='commercial.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PLANEJAMENTO', 'Planejamento'), ('ATIVA', 'Ativa'), ('SUSPENSA', 'Suspensa'), ('CONCLUIDA', 'Concluída')], default='PLANEJAMENTO', max_length=20)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='commercial.contract')),
                ('coordenador_tecnico', models.ForeignKey(limit_choices_to={'profile__setor': 'TECNICO'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
